const pets = [
  {
    id: "34621",
    name: "Baxter",
    type: "Dog",
    breed: "Beagle",
    gender: "Male",
    color: "Tri-color (Black, Brown, White)",
    spay: "Yes",
    age: "5 Years",
    chip: "982000364789210",
    description:
      "Meet Baxter, a lovable Beagle with a knack for sniffing out fun! Baxter was rescued from a shelter and has blossomed into a friendly and outgoing boy. He loves long walks and has a keen sense of smell. He's great with kids and other dogs, making him the perfect family pet. His favorite pastime is chasing squirrels in the park and curling up for naps. Baxter is looking for a loving home where he can share his endless affection and playful spirit.",
    avatar: "../images/beagle.jpeg",
  },
  {
    id: "57281",
    name: "Baxter",
    type: "Dog",
    breed: "Beagle",
    gender: "Male",
    color: "Tri-color (Black, Brown, White)",
    spay: "Yes",
    age: "5 Years",
    chip: "982000364789210",
    description:
      "Meet Baxter, a lovable Beagle with a knack for sniffing out fun! Baxter was rescued from a shelter and has blossomed into a friendly and outgoing boy. He loves long walks and has a keen sense of smell. He's great with kids and other dogs, making him the perfect family pet. His favorite pastime is chasing squirrels in the park and curling up for naps. Baxter is looking for a loving home where he can share his endless affection and playful spirit.",
    avatar: "../images/beagle.jpeg",
  },
  {
    id: "41382",
    name: "Baxter",
    type: "Dog",
    breed: "Beagle",
    gender: "Male",
    color: "Tri-color (Black, Brown, White)",
    spay: "Yes",
    age: "5 Years",
    chip: "982000364789210",
    description:
      "Meet Baxter, a lovable Beagle with a knack for sniffing out fun! Baxter was rescued from a shelter and has blossomed into a friendly and outgoing boy. He loves long walks and has a keen sense of smell. He's great with kids and other dogs, making him the perfect family pet. His favorite pastime is chasing squirrels in the park and curling up for naps. Baxter is looking for a loving home where he can share his endless affection and playful spirit.",
    avatar: "../images/beagle.jpeg",
  },
  {
    id: "62894",
    name: "Baxter",
    type: "Dog",
    breed: "Beagle",
    gender: "Male",
    color: "Tri-color (Black, Brown, White)",
    spay: "Yes",
    age: "5 Years",
    chip: "982000364789210",
    description:
      "Meet Baxter, a lovable Beagle with a knack for sniffing out fun! Baxter was rescued from a shelter and has blossomed into a friendly and outgoing boy. He loves long walks and has a keen sense of smell. He's great with kids and other dogs, making him the perfect family pet. His favorite pastime is chasing squirrels in the park and curling up for naps. Baxter is looking for a loving home where he can share his endless affection and playful spirit.",
    avatar: "../images/beagle.jpeg",
  },
  {
    id: "47920",
    name: "Baxter",
    type: "Dog",
    breed: "Beagle",
    gender: "Male",
    color: "Tri-color (Black, Brown, White)",
    spay: "Yes",
    age: "5 Years",
    chip: "982000364789210",
    description:
      "Meet Baxter, a lovable Beagle with a knack for sniffing out fun! Baxter was rescued from a shelter and has blossomed into a friendly and outgoing boy. He loves long walks and has a keen sense of smell. He's great with kids and other dogs, making him the perfect family pet. His favorite pastime is chasing squirrels in the park and curling up for naps. Baxter is looking for a loving home where he can share his endless affection and playful spirit.",
    avatar: "../images/beagle.jpeg",
  },
  {
    id: "58329",
    name: "Baxter",
    type: "Dog",
    breed: "Beagle",
    gender: "Male",
    color: "Tri-color (Black, Brown, White)",
    spay: "Yes",
    age: "5 Years",
    chip: "982000364789210",
    description:
      "Meet Baxter, a lovable Beagle with a knack for sniffing out fun! Baxter was rescued from a shelter and has blossomed into a friendly and outgoing boy. He loves long walks and has a keen sense of smell. He's great with kids and other dogs, making him the perfect family pet. His favorite pastime is chasing squirrels in the park and curling up for naps. Baxter is looking for a loving home where he can share his endless affection and playful spirit.",
    avatar: "../images/beagle.jpeg",
  },
  {
    id: "49583",
    name: "Baxter",
    type: "Dog",
    breed: "Beagle",
    gender: "Male",
    color: "Tri-color (Black, Brown, White)",
    spay: "Yes",
    age: "5 Years",
    chip: "982000364789210",
    description:
      "Meet Baxter, a lovable Beagle with a knack for sniffing out fun! Baxter was rescued from a shelter and has blossomed into a friendly and outgoing boy. He loves long walks and has a keen sense of smell. He's great with kids and other dogs, making him the perfect family pet. His favorite pastime is chasing squirrels in the park and curling up for naps. Baxter is looking for a loving home where he can share his endless affection and playful spirit.",
    avatar: "../images/beagle.jpeg",
  },
  {
    id: "61029",
    name: "Baxter",
    type: "Dog",
    breed: "Beagle",
    gender: "Male",
    color: "Tri-color (Black, Brown, White)",
    spay: "Yes",
    age: "5 Years",
    chip: "982000364789210",
    description:
      "Meet Baxter, a lovable Beagle with a knack for sniffing out fun! Baxter was rescued from a shelter and has blossomed into a friendly and outgoing boy. He loves long walks and has a keen sense of smell. He's great with kids and other dogs, making him the perfect family pet. His favorite pastime is chasing squirrels in the park and curling up for naps. Baxter is looking for a loving home where he can share his endless affection and playful spirit.",
    avatar: "../images/beagle.jpeg",
  },
  {
    id: "50824",
    name: "Baxter",
    type: "Dog",
    breed: "Beagle",
    gender: "Male",
    color: "Tri-color (Black, Brown, White)",
    spay: "Yes",
    age: "5 Years",
    chip: "982000364789210",
    description:
      "Meet Baxter, a lovable Beagle with a knack for sniffing out fun! Baxter was rescued from a shelter and has blossomed into a friendly and outgoing boy. He loves long walks and has a keen sense of smell. He's great with kids and other dogs, making him the perfect family pet. His favorite pastime is chasing squirrels in the park and curling up for naps. Baxter is looking for a loving home where he can share his endless affection and playful spirit.",
    avatar: "../images/beagle.jpeg",
  },
  {
    id: "63845",
    name: "Baxter",
    type: "Dog",
    breed: "Beagle",
    gender: "Male",
    color: "Tri-color (Black, Brown, White)",
    spay: "Yes",
    age: "5 Years",
    chip: "982000364789210",
    description:
      "Meet Baxter, a lovable Beagle with a knack for sniffing out fun! Baxter was rescued from a shelter and has blossomed into a friendly and outgoing boy. He loves long walks and has a keen sense of smell. He's great with kids and other dogs, making him the perfect family pet. His favorite pastime is chasing squirrels in the park and curling up for naps. Baxter is looking for a loving home where he can share his endless affection and playful spirit.",
    avatar: "../images/beagle.jpeg",
  },
];
